name: Deploy to PyPI

on:
  release:
    types: [ published ]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test_routine:
    name:    Test Python Routine

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]


    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.9'
      - name: Install package
        run:  |
              pip install -U pip setuptools wheel
              pip install -r requirements.txt

      - name: Test package
        run: python -m unittest discover -s ./tests




